steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--tag",
        "gcr.io/$PROJECT_ID/data-science-ui",
        "."
      ]
images:
  - "gcr.io/$PROJECT_ID/data-science-ui"
